[package]
name = "mineswpttd"
version = "0.1.0"
authors = ["Ian Pringle <pard@0x44.pw>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
